SimpleSocialLogin/Models/LoginModel.cs
using System.Collections.Generic;
using Microsoft.Owin.Security;

namespace SimpleSocialLogin.Models
{
    public class LoginModel
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public List<AuthenticationDescription> Providers { get; set; }
    }
}

SimpleSocialLogin/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using Microsoft.Owin.Security;
using SimpleSocialLogin.Models;

namespace SimpleSocialLogin.Controllers
{
    public class AuthController : Controller
    {
        [HttpGet]
        public ActionResult Login()
        {
            var model = new LoginModel();

            var providers =
                HttpContext
                    .GetOwinContext()
                    .Authentication
                    .GetAuthenticationTypes(x => !string.IsNullOrWhiteSpace(x.Caption))
                    .ToList();

            model.Providers = providers;

            return View(model);
        }

        [HttpPost]
        public ActionResult Login(LoginModel model)
        {
            if (model.Username.Equals("jaroslaw", StringComparison.OrdinalIgnoreCase) &&
                model.Password.Equals("stadnicki", StringComparison.OrdinalIgnoreCase))
            {
                var identity = new ClaimsIdentity("ThisCanBeAnythingYouLike"); // the same as in startup
                identity.AddClaims(new List<Claim>
                {
                    new Claim(ClaimTypes.NameIdentifier, model.Username),
                    new Claim(ClaimTypes.Name, model.Username)
                });

                HttpContext.GetOwinContext().Authentication.SignIn(identity);
            }
            return View();
        }

        public ActionResult Logout()
        {
            HttpContext.GetOwinContext().Authentication.SignOut();
            return RedirectToAction("Index", "Home");
        }


        public ActionResult SocialLogin(string id)
        {
            HttpContext.GetOwinContext().Authentication.Challenge(
              new AuthenticationProperties
              {
                  RedirectUri = "/secret"
              },
              id);
            return new HttpUnauthorizedResult();

        }
    }
}

SimpleSocialLogin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SimpleSocialLogin.Controllers
{
    [AllowAnonymous]
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

SimpleSocialLogin/Controllers/SecretController.cs
using System.Web.Mvc;

namespace SimpleSocialLogin.Controllers
{
    [Authorize]
    public class SecretController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

SimpleSocialLogin/Views/Home/Index.cshtml
@inherits System.Web.Mvc.WebViewPage
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
<body>
<div>
    Hello from MVC View
</div>

</body>
</html>

SimpleSocialLogin/Views/Secret/Index.cshtml
@using System.Web.Mvc.Html
@inherits System.Web.Mvc.WebViewPage

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
<body>
    <div>
        Secret page is here
    </div>
    <div>
        @foreach (var claim in ((System.Security.Claims.ClaimsPrincipal)User).Claims)
        {
            <div>
                <span>@claim.Type</span> :
                <span>@claim.Value</span>
            </div>
        }
    </div>

    <div>
        @Html.ActionLink("logout", "Logout", "Auth")
    </div>
</body>
</html>